export const TRADE_CREATE_REQUEST = "TRADE_CREATE_REQUEST";
export const TRADE_CREATE_SUCCESS = "TRADE_CREATE_SUCCESS";
export const TRADE_CREATE_FAIL = "TRADE_CREATE_FAIL";
export const TRADE_CREATE_RESET = "TRADE_CREATE_RESET";

export const TRADE_LIST_MY_REQUEST = "TRADE_LIST_MY_REQUEST";
export const TRADE_LIST_MY_SUCCESS = "TRADE_LIST_MY_SUCCESS";
export const TRADE_LIST_MY_FAIL = "TRADE_LIST_MY_FAIL";
export const TRADE_LIST_MY_RESET = "TRADE_LIST_MY_RESET";
export const TRADE_LIST_MY_UPDATE = "TRADE_LIST_MY_UPDATE";

export const TICKER_LIST_REQUEST = "TICKER_LIST_REQUEST";
export const TICKER_LIST_SUCCESS = "TICKER_LIST_SUCCESS";
export const TICKER_LIST_FAIL = "TICKER_LIST_FAIL";
export const TICKER_LIST_RESET = "TICKER_LIST_RESET";