export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_VERIFICATION_PROFILE_REQUEST = "USER_VERIFICATION_PROFILE_REQUEST";
export const USER_VERIFICATION_PROFILE_SUCCESS = "USER_VERIFICATION_PROFILE_SUCCESS";
export const USER_VERIFICATION_PROFILE_FAIL = "USER_VERIFICATION_PROFILE_FAIL";
export const USER_VERIFICATION_PROFILE_RESET = "USER_VERIFICATION_PROFILE_RESET";


export const USER_RATE_REQUEST = "USER_RATE_REQUEST";
export const USER_RATE_SUCCESS = "USER_RATE_SUCCESS";
export const USER_RATE_FAIL = "USER_RATE_FAIL";
export const USER_RATE_RESET = "USER_RATE_RESET";


export const USER_FA_REQUEST = "USER_FA_REQUEST";
export const USER_FA_SUCCESS = "USER_FA_SUCCESS";
export const USER_FA_FAIL = "USER_FA_FAIL";
export const USER_FA_RESET = "USER_FA_RESET";

export const USER_INVESTLIST_REQUEST = "USER_INVESTLIST_REQUEST";
export const USER_INVESTLIST_SUCCESS = "USER_INVESTLIST_SUCCESS";
export const USER_INVESTLIST_FAIL = "USER_INVESTLIST_FAIL";
export const USER_INVESTLIST_RESET = "USER_INVESTLIST_RESET";

export const INVEST_CREATE_REQUEST = "INVEST_CREATE_REQUEST";
export const INVEST_CREATE_SUCCESS = "INVEST_CREATE_SUCCESS";
export const INVEST_CREATE_FAIL = "INVEST_CREATE_FAIL";
export const INVEST_CREATE_RESET = "INVEST_CREATE_RESET";

export const INVEST_REFUND_REQUEST = "INVEST_REFUND_REQUEST";
export const INVEST_REFUND_SUCCESS = "INVEST_REFUND_SUCCESS";
export const INVEST_REFUND_FAIL = "INVEST_REFUND_FAIL";
export const INVEST_REFUND_RESET = "INVEST_REFUND_RESET";


export const PROMO_ACTIVATE_REQUEST = "PROMO_ACTIVATE_REQUEST";
export const PROMO_ACTIVATE_SUCCESS = "PROMO_ACTIVATE_SUCCESS";
export const PROMO_ACTIVATE_FAIL = "PROMO_ACTIVATE_FAIL";
export const PROMO_ACTIVATE_RESET = "PROMO_ACTIVATE_RESET";

export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const MESSAGE_CREATE_FAIL = "MESSAGE_CREATE_FAIL";
export const MESSAGE_CREATE_RESET = "MESSAGE_CREATE_RESET";

export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST";
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS";
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL";
export const MESSAGE_LIST_RESET = "MESSAGE_LIST_RESET";

export const ALERT_INFO_REQUEST = "ALERT_INFO_REQUEST";
export const ALERT_INFO_SUCCESS = "ALERT_INFO_SUCCESS";
export const ALERT_INFO_FAIL = "ALERT_INFO_FAIL";
export const ALERT_INFO_RESET = "ALERT_INFO_RESET";

export const ALERT_UPDATE_REQUEST = "ALERT_UPDATE_REQUEST";
export const ALERT_UPDATE_SUCCESS = "ALERT_UPDATE_SUCCESS";
export const ALERT_UPDATE_FAIL = "ALERT_UPDATE_FAIL";
export const ALERT_UPDATE_RESET = "ALERT_UPDATE_RESET";




