export const WITHDRAW_CREATE_REQUEST = "WITHDRAW_CREATE_REQUEST";
export const WITHDRAW_CREATE_SUCCESS = "WITHDRAW_CREATE_SUCCESS";
export const WITHDRAW_CREATE_FAIL = "WITHDRAW_CREATE_FAIL";
export const WITHDRAW_CREATE_RESET = "WITHDRAW_CREATE_RESET";

export const WITHDRAW_LIST_MY_REQUEST = "WITHDRAW_LIST_MY_REQUEST";
export const WITHDRAW_LIST_MY_SUCCESS = "WITHDRAW_LIST_MY_SUCCESS";
export const WITHDRAW_LIST_MY_FAIL = "WITHDRAW_LIST_MY_FAIL";
export const WITHDRAW_LIST_MY_RESET = "WITHDRAW_LIST_MY_RESET";

export const TRANSFER_CREATE_REQUEST = "TRANSFER_CREATE_REQUEST";
export const TRANSFER_CREATE_SUCCESS = "TRANSFER_CREATE_SUCCESS";
export const TRANSFER_CREATE_FAIL = "TRANSFER_CREATE_FAIL";
export const TRANSFER_CREATE_RESET = "TRANSFER_CREATE_RESET";

export const TRANSFER_LIST_MY_REQUEST = "TRANSFER_LIST_MY_REQUEST";
export const TRANSFER_LIST_MY_SUCCESS = "TRANSFER_LIST_MY_SUCCESS";
export const TRANSFER_LIST_MY_FAIL = "TRANSFER_LIST_MY_FAIL";
export const TRANSFER_LIST_MY_RESET = "TRANSFER_LIST_MY_RESET";


export const SWAP_LIST_MY_REQUEST = "SWAP_LIST_MY_REQUEST";
export const SWAP_LIST_MY_SUCCESS = "SWAP_LIST_MY_SUCCESS";
export const SWAP_LIST_MY_FAIL = "SWAP_LIST_MY_FAIL";
export const SWAP_LIST_MY_RESET = "SWAP_LIST_MY_RESET";

export const SWAP_CREATE_REQUEST = "SWAP_CREATE_REQUEST";
export const SWAP_CREATE_SUCCESS = "SWAP_CREATE_SUCCESS";
export const SWAP_CREATE_FAIL = "SWAP_CREATE_FAIL";
export const SWAP_CREATE_RESET = "SWAP_CREATE_RESET";

export const DEPOSIT_LIST_MY_REQUEST = "DEPOSIT_LIST_MY_REQUEST";
export const DEPOSIT_LIST_MY_SUCCESS = "DEPOSIT_LIST_MY_SUCCESS";
export const DEPOSIT_LIST_MY_FAIL = "DEPOSIT_LIST_MY_FAIL";
export const DEPOSIT_LIST_MY_RESET = "DEPOSIT_LIST_MY_RESET";
